### ISSUE TITLE
This repository is not up to date

### ISSUE THREAD

**Issue by audunmg** [Velleman/aWFS210#16]
This repository is for app version 1.0 while the official app in the play store is 1.2

Makes it difficult to troubleshoot.

**Comment by BrenuDev** [comment]
Yes you're correct
The app is now based on the same core as the iOS app.
You can find the correct repo here =>https://github.com/Velleman/WFS210-App

**Comment by audunmg** [comment]
Perhaps you could update the description in the play store?
It's the reason i thought this was correct repo but outdated:

https://play.google.com/store/apps/details?id=be.velleman.wfs210

**Comment by BrenuDev** [comment]
Thank you, will do :)
